### ISSUE TITLE
Motion correction for dual channel imaging

### ISSUE THREAD

**Issue by ZeitgeberH** [apasarkar/jnormcorre#7]
Hello,
Could you provide an example demo on  how to apply jnormcorre for  dual channel imaging data motion correction.  For example,  one channel maybe structural, the other is functional.  We want to use the structural channel for motion correction, Then apply the shifts to the function channel.
Thanks!

**Comment by apasarkar** [comment]
Thanks @ZeitgeberH - can look into this, will be in touch shortly with some further questions.

**Comment by apasarkar** [comment]
Hi @ZeitgeberH apologies for the delay. If I understand the use case properly, you have a decent template from your structural channel and you'd like to use that template to motion correct your functional imaging data. In that case, this works nicely (from the new docs):

Create a frame correction object as follows:

`frame_corrector_object = jnormcorre.motion_correction.frame_corrector(template, max_shifts,
                                        strides=strides, overlaps=overlaps,
                                                max_deviation_rigid, min_mov=0)`

Pass in your data like this: 

`frame_corrector_object.register_frames(your_data, pw_rigid=pw_rigid)`

Let me know if this works -- otherwise just reopen the request and we can talk more about it.
